// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5ywgm418t5vPvJnrXaY5jc_QexvbPDMA',
    appId: '1:395691303400:web:ff74f5a1821e107333445d',
    messagingSenderId: '395691303400',
    projectId: 'fastlane-f20ce',
    authDomain: 'fastlane-f20ce.firebaseapp.com',
    storageBucket: 'fastlane-f20ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ujWBezg7PCb07Pu_x2WyXvLQYVZVyEs',
    appId: '1:395691303400:android:e69d031b4d6658f733445d',
    messagingSenderId: '395691303400',
    projectId: 'fastlane-f20ce',
    storageBucket: 'fastlane-f20ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApfNKnnBsgTQm2r3d6RtUEiIzggBYdxiw',
    appId: '1:395691303400:ios:ec127ec74b9e8eb133445d',
    messagingSenderId: '395691303400',
    projectId: 'fastlane-f20ce',
    storageBucket: 'fastlane-f20ce.firebasestorage.app',
    iosBundleId: 'com.example.fastlane',
  );
}
