# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
 desc "distribut to firebase app distribution"
 lane :distribut do
   sh 'flutter clean'
   sh 'flutter build apk --release'
  firebase_app_distribution(
    app: "1:395691303400:android:e69d031b4d6658f733445d",
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],

    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/apk/release/app-release.apk",
    testers: 'manarsalah3200@g,ail.com'
  )
  
   
  end
end
